<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INPC0TB3ZZ" name="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status" tests="10" failures="0" timestamp="2019-12-10T13:25:22 IST" time="256.234" errors="1">
  <testcase name="login" time="15.690" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_In_Compliance" time="41.787" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_total_Compliance" time="30.828" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_In_Complaince_With_delay" time="10.453" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_Non_Compliance" time="32.268" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_Not_Applicable" time="16.933" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at gRCenforce.generalUtils.workflow_history(generalUtils.java:95)
at gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status.view_Not_Applicable(gRCenforceView_Total_Compliance_Tasks_Status.java:131)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- view_Not_Applicable -->
  <testcase name="view_Not_Submitted" time="35.812" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_due" time="28.833" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="view_overdue" time="26.788" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
  <testcase name="logout" time="16.842" classname="gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status"/>
</testsuite> <!-- gRCenforce.gRCenforceView_Total_Compliance_Tasks_Status -->
